title: Librarian Robot
description: A 4-DOF articulated robot arm designed to autonomously pick and place books on a library shelf
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
